### ISSUE TITLE
[Bug] Serve not working in windows 10 (64 Bit)

### ISSUE THREAD

**Issue by 0xsuid** [go-shiori/shiori#155]
## Bug
I've tried to start server but it failed, below is the log:
```
shiori-windows-amd64.exe serve
panic: Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub

goroutine 1 [running]:
github.com/jmoiron/sqlx.MustConnect(...)
        /home/radhi/Development/SDK/Go/pkg/mod/github.com/jmoiron/sqlx@v1.2.0/sqlx.go:650
github.com/go-shiori/shiori/internal/database.OpenSQLiteDatabase(0xc00007ee00, 0x35, 0x0, 0x0, 0x0)
        /home/radhi/Development/Projects/Go/shiori/internal/database/sqlite.go:23 +0x442
github.com/go-shiori/shiori/internal/cmd.openDatabase(0xc00007c360, 0x2b, 0x1ff, 0x0)
        /home/radhi/Development/Projects/Go/shiori/internal/cmd/root.go:114 +0xe4
github.com/go-shiori/shiori/internal/cmd.preRunRootHandler(0xc000364f00, 0x10e8ec0, 0x0, 0x0)
        /home/radhi/Development/Projects/Go/shiori/internal/cmd/root.go:62 +0x1a2
github.com/spf13/cobra.(*Command).execute(0xc000364f00, 0x10e8ec0, 0x0, 0x0, 0xc000364f00, 0x10e8ec0)
        /home/radhi/Development/SDK/Go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:810 +0x228
github.com/spf13/cobra.(*Command).ExecuteC(0xc000143680, 0x0, 0x0, 0x92c195)
        /home/radhi/Development/SDK/Go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x303
github.com/spf13/cobra.(*Command).Execute(...)
        /home/radhi/Development/SDK/Go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main()
        /home/radhi/Development/Projects/Go/shiori/main.go:18 +0x2f
```

## Fix:
- **CGO_ENABLED=1** needs to enabled when compiling binary

**Comment by zouhair** [comment]
Same here

**Comment by 0xsuid** [comment]
Update:

I've build binaries and is available on my forked branch - [0xsuid/shiori](https://github.com/0xsuid/shiori/releases/tag/v1.5.1)

**Comment by RadhiFadlillah** [comment]
@0xsuid oh yeah, I forgot to enable cgo while cross compiling it. 

I've updated the released binary, could you check it out ?

**Comment by 0xsuid** [comment]
@RadhiFadlillah It is working now.
